all:
	#gcc -o family_old family_old.c -no-pie -fstack-protector -z noexecstack -static
	gcc -o family family.c -no-pie -fstack-protector -z noexecstack -static

clear:
	rm -f family
	#rm -f family_old
