version: '3'
services:
    helloctf:
        container_name: helloctf
        build: .
        volumes:
            - ./share/:/home/helloctf:ro
            - ./xinetd:/etc/xinetd.d/helloctf:ro
        ports:
            - "11001:8787"

